import sys
sys.stdout.reconfigure(encoding='utf-8')

FE = r"d:\Diverse\Facultate CSIE\Cercetare\Cercetare doctorat\FINISHED\Proiect 3 - Photo Categ App\App Project\MyOwnApp\file_explorer.py"

with open(FE, 'r', encoding='utf-8') as f:
    lines = f.readlines()

print(f"Lines before: {len(lines)}")

# ── Patch 1: clear_search (lines 3336 and 3340, 1-indexed) ──────────
lines[3335] = '        self._redraw_tag_palette()\n'
lines[3339] = "                text='Click tag = include  \xb7  again = exclude  \xb7  again = clear',\n"

# ── Patch 2: replace _add_tag_chip + _cycle_chip + _rebuild_chips + _remove_chip
# 1-indexed lines 3110-3159 → 0-indexed 3109:3159
new_chip = (
    "    def _add_tag_chip(self, tag: str, state: str = '+'):\n"
    "        \"\"\"Add or update a tag. state: '+' = include, '-' = exclude.\"\"\"\n"
    "        if not tag:\n"
    "            return\n"
    "        self._tag_states[tag] = state\n"
    "        self._redraw_tag_palette()\n"
    "        if self._search_active or self._tag_states:\n"
    "            self.perform_tag_search()\n"
    "\n"
    "    def _remove_chip(self, tag: str):\n"
    "        self._tag_states.pop(tag, None)\n"
    "        self._redraw_tag_palette()\n"
    "        if self._search_active or self._tag_states:\n"
    "            self.perform_tag_search()\n"
    "        elif not self._tag_states:\n"
    "            self.clear_search()\n"
    "\n"
)
lines[3109:3159] = [new_chip]

# ── Patch 3: replace _build_search_bar … _add_selected_all_tag
# 1-indexed lines 2963-3088 → 0-indexed 2962:3088
new_bar = (
    "    def _build_search_bar(self, parent=None):\n"
    "        \"\"\"Advanced tag-search bar with a single-canvas chip palette.\"\"\"\n"
    "        if parent is None:\n"
    "            parent = self.root\n"
    "        outer = ttk.Frame(parent, relief='groove', borderwidth=1)\n"
    "        outer.pack(fill=tk.BOTH, expand=True, padx=5, pady=(0, 2))\n"
    "        self._search_bar_frame = outer\n"
    "\n"
    "        # Row 1: tag-name entry + autocomplete + sort + action buttons\n"
    "        row1 = ttk.Frame(outer)\n"
    "        row1.pack(fill=tk.X, padx=4, pady=(3, 1))\n"
    "\n"
    "        ttk.Label(row1, text='\U0001f50d', font=('Arial', 11)).pack(side=tk.LEFT, padx=(0, 4))\n"
    "\n"
    "        self.search_var = tk.StringVar()\n"
    "        self.search_entry = ttk.Entry(row1, textvariable=self.search_var, width=28,\n"
    "                                      font=('Arial', 10))\n"
    "        self.search_entry.pack(side=tk.LEFT, padx=(0, 4))\n"
    "        self.search_entry.bind('<Return>', lambda e: self._commit_search_token())\n"
    "        self.search_entry.bind('<Escape>', lambda e: self._hide_tag_suggestions())\n"
    "        self.search_var.trace_add('write', self._on_search_entry_change)\n"
    "\n"
    "        ttk.Button(row1, text='Add tag ↵',\n"
    "                   command=self._commit_search_token).pack(side=tk.LEFT, padx=2)\n"
    "\n"
    "        ttk.Separator(row1, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=6)\n"
    "\n"
    "        ttk.Label(row1, text='Sort:', font=('Arial', 9)).pack(side=tk.LEFT)\n"
    "        self._sort_var = tk.StringVar(value='name')\n"
    "        ttk.Combobox(row1, textvariable=self._sort_var, width=8, state='readonly',\n"
    "                     values=['name', 'date', 'size'],\n"
    "                     font=('Arial', 9)).pack(side=tk.LEFT, padx=2)\n"
    "\n"
    "        self._sort_asc_var = tk.BooleanVar(value=True)\n"
    "        self._sort_dir_btn = ttk.Button(row1, text='↑ Asc', width=6,\n"
    "                                        command=self._toggle_sort_dir)\n"
    "        self._sort_dir_btn.pack(side=tk.LEFT, padx=2)\n"
    "\n"
    "        ttk.Separator(row1, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=6)\n"
    "\n"
    "        ttk.Button(row1, text='Search',\n"
    "                   command=self.perform_tag_search).pack(side=tk.LEFT, padx=2)\n"
    "        self.search_clear_btn = ttk.Button(row1, text='✕ Clear',\n"
    "                                           command=self.clear_search, state=tk.DISABLED)\n"
    "        self.search_clear_btn.pack(side=tk.LEFT, padx=2)\n"
    "\n"
    "        self.search_status_label = ttk.Label(\n"
    "            row1, text='Click tag = include  \xb7  again = exclude  \xb7  again = clear',\n"
    "            foreground='gray', font=('Arial', 9))\n"
    "        self.search_status_label.pack(side=tk.LEFT, padx=(10, 0))\n"
    "\n"
    "        # Row 2: palette filter entry + color legend\n"
    "        row2 = ttk.Frame(outer)\n"
    "        row2.pack(fill=tk.X, padx=4, pady=(2, 3))\n"
    "\n"
    "        ttk.Label(row2, text='Filter:', font=('Arial', 9)).pack(side=tk.LEFT, padx=(0, 3))\n"
    "        self._tag_filter_var = tk.StringVar()\n"
    "        ttk.Entry(row2, textvariable=self._tag_filter_var, width=24,\n"
    "                  font=('Arial', 9)).pack(side=tk.LEFT)\n"
    "        self._tag_filter_var.trace_add('write', lambda *_: self._schedule_palette_redraw())\n"
    "\n"
    "        ttk.Button(row2, text='Refresh', width=8,\n"
    "                   command=self._refresh_advanced_tag_sources).pack(side=tk.LEFT, padx=(8, 0))\n"
    "\n"
    "        legend = ttk.Frame(row2)\n"
    "        legend.pack(side=tk.RIGHT, padx=(0, 4))\n"
    "        for _lc, _ll in (('#e8851a', 'Include'), ('#c62828', 'Exclude')):\n"
    "            tk.Frame(legend, bg=_lc, width=12, height=12).pack(side=tk.LEFT, padx=(8, 2))\n"
    "            ttk.Label(legend, text=_ll, font=('Arial', 8)).pack(side=tk.LEFT)\n"
    "\n"
    "        # Canvas palette — all chips drawn as primitives on one canvas\n"
    "        palette_outer = ttk.Frame(outer)\n"
    "        palette_outer.pack(fill=tk.BOTH, expand=True, padx=4, pady=(0, 4))\n"
    "\n"
    "        self._palette_canvas = tk.Canvas(palette_outer, bg='#fafafa',\n"
    "                                          highlightthickness=0, relief='flat')\n"
    "        _pal_vsb = ttk.Scrollbar(palette_outer, orient='vertical',\n"
    "                                  command=self._palette_canvas.yview)\n"
    "        self._palette_canvas.configure(yscrollcommand=_pal_vsb.set)\n"
    "        _pal_vsb.pack(side=tk.RIGHT, fill=tk.Y)\n"
    "        self._palette_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)\n"
    "\n"
    "        self._palette_canvas.bind('<Configure>',\n"
    "                                   lambda _e: self._schedule_palette_redraw())\n"
    "        self._palette_canvas.bind('<Button-1>', self._on_palette_click)\n"
    "        self._palette_canvas.bind(\n"
    "            '<MouseWheel>',\n"
    "            lambda e: self._palette_canvas.yview_scroll(-1 * (e.delta // 120), 'units'))\n"
    "        self._palette_canvas.bind(\n"
    "            '<Button-4>', lambda _e: self._palette_canvas.yview_scroll(-1, 'units'))\n"
    "        self._palette_canvas.bind(\n"
    "            '<Button-5>', lambda _e: self._palette_canvas.yview_scroll(1, 'units'))\n"
    "\n"
    "        # Internal state\n"
    "        self._tag_states:           dict   = {}\n"
    "        self._palette_all_tags:     list   = []\n"
    "        self._palette_chip_regions: list   = []\n"
    "        self._palette_redraw_job:   object = None\n"
    "        self._palette_font_obj:     object = None\n"
    "        self._search_active:        bool   = False\n"
    "        self._last_search_results:  list   = []\n"
    "\n"
    "        self._suggest_popup:   tk.Toplevel | None = None  # type: ignore[assignment]\n"
    "        try:\n"
    "            lbox = tk.Listbox(self.root)\n"
    "            lbox.pack_forget()\n"
    "        except Exception:\n"
    "            lbox = None\n"
    "        self._suggest_listbox: tk.Listbox | None = lbox  # type: ignore[assignment]\n"
    "\n"
    "        self._refresh_advanced_tag_sources()\n"
    "\n"
    "    # Tag palette: data loading\n"
    "\n"
    "    def _refresh_advanced_tag_sources(self):\n"
    "        \"\"\"Reload the full tag list from DB in a background thread.\"\"\"\n"
    "        def _worker() -> None:\n"
    "            try:\n"
    "                tags = sorted(row['tag_name'] for row in metadata_store.get_all_tags())\n"
    "            except Exception:\n"
    "                tags = []\n"
    "            try:\n"
    "                self.root.after(0, lambda: self._apply_palette_tags(tags))\n"
    "            except Exception:\n"
    "                pass\n"
    "        threading.Thread(target=_worker, daemon=True).start()\n"
    "\n"
    "    def _apply_palette_tags(self, tags: list) -> None:\n"
    "        self._palette_all_tags = tags\n"
    "        self._redraw_tag_palette()\n"
    "\n"
    "    # Tag palette: canvas drawing\n"
    "\n"
    "    def _get_palette_font(self):\n"
    "        if self._palette_font_obj is None:\n"
    "            from tkinter import font as _tkfont\n"
    "            self._palette_font_obj = _tkfont.Font(family='Arial', size=9, weight='bold')\n"
    "        return self._palette_font_obj\n"
    "\n"
    "    def _schedule_palette_redraw(self) -> None:\n"
    "        \"\"\"Debounce rapid redraws (resize, filter typing).\"\"\"\n"
    "        if self._palette_redraw_job is not None:\n"
    "            try:\n"
    "                self.root.after_cancel(self._palette_redraw_job)\n"
    "            except Exception:\n"
    "                pass\n"
    "        self._palette_redraw_job = self.root.after(30, self._redraw_tag_palette)\n"
    "\n"
    "    def _redraw_tag_palette(self) -> None:\n"
    "        \"\"\"Redraw all tag chips on the single palette canvas.\"\"\"\n"
    "        self._palette_redraw_job = None\n"
    "        if not hasattr(self, '_palette_canvas'):\n"
    "            return\n"
    "        c = self._palette_canvas\n"
    "        c.delete('all')\n"
    "        self._palette_chip_regions = []\n"
    "\n"
    "        canvas_w = c.winfo_width()\n"
    "        if canvas_w < 60:\n"
    "            canvas_w = 400\n"
    "\n"
    "        filt = getattr(self, '_tag_filter_var', None)\n"
    "        filt_text = filt.get().lower().strip() if filt else ''\n"
    "        extra = sorted(t for t in self._tag_states if t not in self._palette_all_tags)\n"
    "        all_display = sorted(set(self._palette_all_tags) | set(extra))\n"
    "        if filt_text:\n"
    "            all_display = [t for t in all_display if filt_text in t.lower()]\n"
    "\n"
    "        if not all_display:\n"
    "            msg = 'No tags match.' if filt_text else 'No tags found — click Refresh.'\n"
    "            c.create_text(10, 12, anchor='nw', text=msg,\n"
    "                          fill='#999999', font=('Arial', 9))\n"
    "            c.configure(scrollregion=(0, 0, canvas_w, 36))\n"
    "            return\n"
    "\n"
    "        font   = self._get_palette_font()\n"
    "        CHIP_H = 26\n"
    "        PAD_X  = 10\n"
    "        GAP_X  = 5\n"
    "        GAP_Y  = 5\n"
    "        RADIUS = 6\n"
    "        x = y  = 6\n"
    "\n"
    "        for tag in all_display:\n"
    "            state = self._tag_states.get(tag, '')\n"
    "            if state == '+':\n"
    "                bg, border, fg = '#e8851a', '#c86a00', '#ffffff'\n"
    "            elif state == '-':\n"
    "                bg, border, fg = '#c62828', '#9a1c1c', '#ffffff'\n"
    "            else:\n"
    "                bg, border, fg = '#ffffff', '#888888', '#222222'\n"
    "\n"
    "            chip_w = font.measure(tag) + PAD_X * 2\n"
    "\n"
    "            if x + chip_w > canvas_w - 6 and x > 6:\n"
    "                x  = 6\n"
    "                y += CHIP_H + GAP_Y\n"
    "\n"
    "            x1, y1, x2, y2 = x, y, x + chip_w, y + CHIP_H\n"
    "            self._draw_palette_chip(c, x1, y1, x2, y2, bg, border, fg, tag, RADIUS, font)\n"
    "            self._palette_chip_regions.append((x1, y1, x2, y2, tag))\n"
    "            x += chip_w + GAP_X\n"
    "\n"
    "        total_h = y + CHIP_H + GAP_Y + 6\n"
    "        c.configure(scrollregion=(0, 0, canvas_w, total_h))\n"
    "\n"
    "    @staticmethod\n"
    "    def _draw_palette_chip(canvas, x1, y1, x2, y2, bg, border, fg, text, r, font):\n"
    "        \"\"\"Draw one rounded-rectangle chip on a canvas.\"\"\"\n"
    "        pts = [\n"
    "            x1 + r, y1,      x2 - r, y1,\n"
    "            x2,     y1,      x2,     y1 + r,\n"
    "            x2,     y2 - r,  x2,     y2,\n"
    "            x2 - r, y2,      x1 + r, y2,\n"
    "            x1,     y2,      x1,     y2 - r,\n"
    "            x1,     y1 + r,  x1,     y1,\n"
    "        ]\n"
    "        canvas.create_polygon(pts, smooth=True, fill=bg, outline=border, width=1.5)\n"
    "        canvas.create_text((x1 + x2) // 2, (y1 + y2) // 2,\n"
    "                           text=text, fill=fg, font=font, anchor='center')\n"
    "\n"
    "    def _on_palette_click(self, event) -> None:\n"
    "        cx = self._palette_canvas.canvasx(event.x)\n"
    "        cy = self._palette_canvas.canvasy(event.y)\n"
    "        for x1, y1, x2, y2, tag in self._palette_chip_regions:\n"
    "            if x1 <= cx <= x2 and y1 <= cy <= y2:\n"
    "                self._cycle_palette_tag(tag)\n"
    "                return\n"
    "\n"
    "    def _cycle_palette_tag(self, tag: str) -> None:\n"
    "        current = self._tag_states.get(tag, '')\n"
    "        if current == '':\n"
    "            self._tag_states[tag] = '+'\n"
    "        elif current == '+':\n"
    "            self._tag_states[tag] = '-'\n"
    "        else:\n"
    "            self._tag_states.pop(tag, None)\n"
    "        self._redraw_tag_palette()\n"
    "        if self._search_active or self._tag_states:\n"
    "            self.perform_tag_search()\n"
    "\n"
)
lines[2962:3088] = [new_bar]

with open(FE, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f"Done. Lines after: {len(lines)}")
